name: Dispatch Blog Content Update

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    name: Dispatch Blog Update
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch repository_dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: kesaruhasun/kesaru_me
          event-type: update_blog_content
